---
- hosts: localhost
  become: False
  gather_facts: False
  vars:
    test_var: Test
    not_used_variable: "{{ var_that_does_not_exists }}"
  tasks:
    - name: Test template
      debug:
        msg: "{{ lookup('template', 'test.j2') }}"
